import { createContext, useContext, useEffect, useMemo, useState } from 'react';

const LANGUAGE_STORAGE_KEY = 'qr_menu_language';
const THEME_STORAGE_KEY = 'qr_menu_theme';

export const languages = [
  { value: 'tr', label: 'Türkçe' },
  { value: 'en', label: 'English' },
  { value: 'de', label: 'Deutsch' },
];

const translations = {
  tr: {
    common: {
      language: 'Dil',
      theme: 'Tema',
      light: 'Açık',
      dark: 'Koyu',
      refresh: 'Yenile',
      logout: 'Çıkış',
      save: 'Kaydet',
      cancel: 'Vazgeç',
      close: 'Kapat',
      openMenu: 'Menüyü Aç',
      staff: 'Personel',
      admin: 'Yönetici',
    },
    login: {
      title: 'Admin Girişi',
      subtitle: 'Yetkili hesabınızla devam edin.',
      description: 'QR menü, mutfak ve servis operasyonları için yönetim paneli.',
      email: 'E-posta',
      emailRequired: 'E-posta zorunlu',
      password: 'Şifre',
      passwordRequired: 'Şifre zorunlu',
      submit: 'Giriş Yap',
      success: 'Giriş başarılı',
    },
    admin: {
      managementPanel: 'Yönetim Paneli',
      operationsPanel: 'Operasyon Paneli',
      pending: 'Bekleyen',
      activeOrder: 'Aktif Sipariş',
      liveOperation: 'Canlı Operasyon',
      adminSubtitle: 'Mutfak, sipariş, masa, QR, menü ve ekip yönetimi',
      staffSubtitle: 'Mutfak, sipariş ve müşteri istekleri',
      realtimeOn: 'Canlı bağlantı açık',
      realtimeOff: 'Canlı bağlantı kapalı',
      soundTest: 'Ses Testi',
      enableSound: 'Sesi Aç',
      tables: 'masa',
      activeOrders: 'aktif sipariş',
      served: 'servis edildi',
      ratings: 'puan',
      tableMetric: 'Masa',
      productMetric: 'Ürün',
      orderMetric: 'Sipariş',
      servedMetric: 'Servis Edildi',
      pendingRequestMetric: 'Bekleyen İstek',
      overallRating: 'Genel Puan',
      tabs: {
        overview: 'Genel Bakış',
        orders: 'Sipariş Geçmişi',
        requests: 'İstek Geçmişi',
        feedbacks: 'Puanlar',
        tables: 'Masalar ve QR',
        categories: 'Kategoriler',
        products: 'Ürünler',
        users: 'Ekip',
        restaurant: 'Restoran',
      },
    },
    menu: {
      table: 'Masa',
      hero: 'QR menüden sipariş verin, garson çağırın ve sipariş durumunu anlık takip edin.',
      callWaiter: 'Garson Çağır',
      requestBill: 'Hesap İste',
      cart: 'Sepet',
      menu: 'Menü',
      myOrders: 'Siparişlerim',
      search: 'Ürün ara',
      add: 'Ekle',
      emptyCategory: 'Bu kategoride ürün yok',
      noOrders: 'Henüz sipariş verilmedi',
      unavailableTitle: 'Menü erişime kapalı',
      unavailableSubtitle: 'Bu QR kod için aktif bir masa menüsü bulunamadı.',
      order: 'Sipariş',
      total: 'Toplam',
      cancelled: 'Sipariş iptal edildi',
      cancelledDescription: 'Restoran siparişinizi iptal etti.',
      feedbackReceived: 'Değerlendirmeniz alındı',
      feedbackDescription: 'Geri bildiriminiz restoran yönetimine iletildi.',
      cartSelected: 'ürün seçildi',
      cartDraft: 'Siparişiniz burada hazırlanır',
      payableTotal: 'Ödenecek Toplam',
      placeOrder: 'Sipariş Ver',
      cartEmpty: 'Sepet boş',
      productNote: 'Ürün notu',
      orderNote: 'Sipariş Notu',
      addedToCart: 'sepete eklendi',
      orderReceived: 'Sipariş alındı',
      orderSent: 'Siparişiniz mutfağa iletildi. Durumunu bu ekrandan takip edebilirsiniz.',
      waiterCalled: 'Garson çağrıldı',
      billSent: 'Hesap isteği gönderildi',
      billNote: 'Hesap isteğine not ekleyin',
      waiterNote: 'Garsona mesaj ekleyin',
      send: 'Gönder',
      unitPrice: 'birim fiyat',
      orderNotePlaceholder: 'Örn. hepsi birlikte gelsin',
      feedbackThanks: 'Puanınız için teşekkürler',
    },
    status: {
      PENDING: 'Alındı',
      PREPARING: 'Hazırlanıyor',
      READY: 'Hazır',
      SERVED: 'Servis Edildi',
      CANCELLED: 'İptal',
    },
  },
  en: {
    common: {
      language: 'Language',
      theme: 'Theme',
      light: 'Light',
      dark: 'Dark',
      refresh: 'Refresh',
      logout: 'Logout',
      save: 'Save',
      cancel: 'Cancel',
      close: 'Close',
      openMenu: 'Open Menu',
      staff: 'Staff',
      admin: 'Admin',
    },
    login: {
      title: 'Admin Login',
      subtitle: 'Continue with your authorized account.',
      description: 'Management panel for QR menu, kitchen, and service operations.',
      email: 'Email',
      emailRequired: 'Email is required',
      password: 'Password',
      passwordRequired: 'Password is required',
      submit: 'Sign In',
      success: 'Signed in successfully',
    },
    admin: {
      managementPanel: 'Management Panel',
      operationsPanel: 'Operations Panel',
      pending: 'Pending',
      activeOrder: 'Active Orders',
      liveOperation: 'Live Operation',
      adminSubtitle: 'Kitchen, orders, tables, QR, menu, and team management',
      staffSubtitle: 'Kitchen, orders, and customer requests',
      realtimeOn: 'Live connection on',
      realtimeOff: 'Live connection off',
      soundTest: 'Test Sound',
      enableSound: 'Enable Sound',
      tables: 'tables',
      activeOrders: 'active orders',
      served: 'served',
      ratings: 'ratings',
      tableMetric: 'Tables',
      productMetric: 'Products',
      orderMetric: 'Orders',
      servedMetric: 'Served',
      pendingRequestMetric: 'Pending Requests',
      overallRating: 'Overall Rating',
      tabs: {
        overview: 'Overview',
        orders: 'Order History',
        requests: 'Request History',
        feedbacks: 'Ratings',
        tables: 'Tables and QR',
        categories: 'Categories',
        products: 'Products',
        users: 'Team',
        restaurant: 'Restaurant',
      },
    },
    menu: {
      table: 'Table',
      hero: 'Order from the QR menu, call a waiter, and track your order live.',
      callWaiter: 'Call Waiter',
      requestBill: 'Request Bill',
      cart: 'Cart',
      menu: 'Menu',
      myOrders: 'My Orders',
      search: 'Search products',
      add: 'Add',
      emptyCategory: 'No products in this category',
      noOrders: 'No orders yet',
      unavailableTitle: 'Menu unavailable',
      unavailableSubtitle: 'No active table menu was found for this QR code.',
      order: 'Order',
      total: 'Total',
      cancelled: 'Order cancelled',
      cancelledDescription: 'The restaurant cancelled your order.',
      feedbackReceived: 'Your rating was received',
      feedbackDescription: 'Your feedback was sent to restaurant management.',
      cartSelected: 'items selected',
      cartDraft: 'Your order will be prepared here',
      payableTotal: 'Amount Due',
      placeOrder: 'Place Order',
      cartEmpty: 'Cart is empty',
      productNote: 'Product note',
      orderNote: 'Order Note',
      addedToCart: 'added to cart',
      orderReceived: 'Order received',
      orderSent: 'Your order was sent to the kitchen. You can track its status here.',
      waiterCalled: 'Waiter called',
      billSent: 'Bill request sent',
      billNote: 'Add a note to the bill request',
      waiterNote: 'Add a message for the waiter',
      send: 'Send',
      unitPrice: 'unit price',
      orderNotePlaceholder: 'E.g. bring everything together',
      feedbackThanks: 'Thanks for your rating',
    },
    status: {
      PENDING: 'Received',
      PREPARING: 'Preparing',
      READY: 'Ready',
      SERVED: 'Served',
      CANCELLED: 'Cancelled',
    },
  },
  de: {
    common: {
      language: 'Sprache',
      theme: 'Design',
      light: 'Hell',
      dark: 'Dunkel',
      refresh: 'Aktualisieren',
      logout: 'Abmelden',
      save: 'Speichern',
      cancel: 'Abbrechen',
      close: 'Schließen',
      openMenu: 'Menü Öffnen',
      staff: 'Personal',
      admin: 'Admin',
    },
    login: {
      title: 'Admin Anmeldung',
      subtitle: 'Mit autorisiertem Konto fortfahren.',
      description: 'Verwaltung für QR-Menü, Küche und Serviceabläufe.',
      email: 'E-Mail',
      emailRequired: 'E-Mail ist erforderlich',
      password: 'Passwort',
      passwordRequired: 'Passwort ist erforderlich',
      submit: 'Anmelden',
      success: 'Erfolgreich angemeldet',
    },
    admin: {
      managementPanel: 'Verwaltung',
      operationsPanel: 'Betrieb',
      pending: 'Wartend',
      activeOrder: 'Aktive Bestellungen',
      liveOperation: 'Live-Betrieb',
      adminSubtitle: 'Küche, Bestellungen, Tische, QR, Menü und Teamverwaltung',
      staffSubtitle: 'Küche, Bestellungen und Gästewünsche',
      realtimeOn: 'Live-Verbindung aktiv',
      realtimeOff: 'Live-Verbindung aus',
      soundTest: 'Ton Testen',
      enableSound: 'Ton Aktivieren',
      tables: 'Tische',
      activeOrders: 'aktive Bestellungen',
      served: 'serviert',
      ratings: 'Bewertungen',
      tableMetric: 'Tische',
      productMetric: 'Produkte',
      orderMetric: 'Bestellungen',
      servedMetric: 'Serviert',
      pendingRequestMetric: 'Wartende Wünsche',
      overallRating: 'Gesamtbewertung',
      tabs: {
        overview: 'Übersicht',
        orders: 'Bestellverlauf',
        requests: 'Anfrageverlauf',
        feedbacks: 'Bewertungen',
        tables: 'Tische und QR',
        categories: 'Kategorien',
        products: 'Produkte',
        users: 'Team',
        restaurant: 'Restaurant',
      },
    },
    menu: {
      table: 'Tisch',
      hero: 'Bestellen Sie per QR-Menü, rufen Sie den Service und verfolgen Sie Ihre Bestellung live.',
      callWaiter: 'Service Rufen',
      requestBill: 'Rechnung Anfordern',
      cart: 'Warenkorb',
      menu: 'Menü',
      myOrders: 'Meine Bestellungen',
      search: 'Produkte suchen',
      add: 'Hinzufügen',
      emptyCategory: 'Keine Produkte in dieser Kategorie',
      noOrders: 'Noch keine Bestellungen',
      unavailableTitle: 'Menü nicht verfügbar',
      unavailableSubtitle: 'Für diesen QR-Code wurde kein aktives Tischmenü gefunden.',
      order: 'Bestellung',
      total: 'Gesamt',
      cancelled: 'Bestellung storniert',
      cancelledDescription: 'Das Restaurant hat Ihre Bestellung storniert.',
      feedbackReceived: 'Ihre Bewertung wurde erfasst',
      feedbackDescription: 'Ihr Feedback wurde an die Restaurantleitung gesendet.',
      cartSelected: 'Artikel ausgewählt',
      cartDraft: 'Ihre Bestellung wird hier vorbereitet',
      payableTotal: 'Zu Zahlen',
      placeOrder: 'Bestellen',
      cartEmpty: 'Warenkorb ist leer',
      productNote: 'Produktnotiz',
      orderNote: 'Bestellnotiz',
      addedToCart: 'zum Warenkorb hinzugefügt',
      orderReceived: 'Bestellung empfangen',
      orderSent: 'Ihre Bestellung wurde an die Küche gesendet. Sie können den Status hier verfolgen.',
      waiterCalled: 'Service wurde gerufen',
      billSent: 'Rechnungsanfrage gesendet',
      billNote: 'Notiz zur Rechnungsanfrage hinzufügen',
      waiterNote: 'Nachricht an den Service hinzufügen',
      send: 'Senden',
      unitPrice: 'Stückpreis',
      orderNotePlaceholder: 'Z. B. alles zusammen bringen',
      feedbackThanks: 'Danke für Ihre Bewertung',
    },
    status: {
      PENDING: 'Empfangen',
      PREPARING: 'In Zubereitung',
      READY: 'Bereit',
      SERVED: 'Serviert',
      CANCELLED: 'Storniert',
    },
  },
};

const PreferencesContext = createContext(null);

export function PreferencesProvider({ children }) {
  const [language, setLanguageState] = useState(() => localStorage.getItem(LANGUAGE_STORAGE_KEY) || 'tr');
  const [themeMode, setThemeModeState] = useState(() => localStorage.getItem(THEME_STORAGE_KEY) || 'light');

  useEffect(() => {
    localStorage.setItem(LANGUAGE_STORAGE_KEY, language);
    document.documentElement.lang = language;
  }, [language]);

  useEffect(() => {
    localStorage.setItem(THEME_STORAGE_KEY, themeMode);
    document.documentElement.dataset.theme = themeMode;
  }, [themeMode]);

  const value = useMemo(() => {
    const dictionary = translations[language] || translations.tr;
    const t = (key) => key.split('.').reduce((current, part) => current?.[part], dictionary) || key;

    return {
      language,
      setLanguage: setLanguageState,
      themeMode,
      setThemeMode: setThemeModeState,
      toggleTheme: () => setThemeModeState((current) => (current === 'dark' ? 'light' : 'dark')),
      t,
    };
  }, [language, themeMode]);

  return <PreferencesContext.Provider value={value}>{children}</PreferencesContext.Provider>;
}

export function usePreferences() {
  const context = useContext(PreferencesContext);
  if (!context) {
    throw new Error('usePreferences must be used within PreferencesProvider');
  }
  return context;
}
