import { createContext, useContext, useEffect, useMemo, useState } from 'react';

const LANGUAGE_STORAGE_KEY = 'qr_menu_language';
const THEME_STORAGE_KEY = 'qr_menu_theme';

export const languages = [
  { value: 'tr', label: 'Türkçe' },
  { value: 'en', label: 'English' },
  { value: 'de', label: 'Deutsch' },
  { value: 'ar', label: 'العربية' },
];

export const languageDirections = {
  ar: 'rtl',
};

const translations = {
  tr: {
    common: {
      language: 'Dil',
      theme: 'Tema',
      light: 'Açık',
      dark: 'Koyu',
      refresh: 'Yenile',
      logout: 'Çıkış',
      save: 'Kaydet',
      cancel: 'Vazgeç',
      close: 'Kapat',
      openMenu: 'Menüyü Aç',
      staff: 'Personel',
      admin: 'Yönetici',
    },
    login: {
      title: 'Admin Girişi',
      subtitle: 'Yetkili hesabınızla devam edin.',
      description: 'QR menü, mutfak ve servis operasyonları için yönetim paneli.',
      email: 'E-posta',
      emailRequired: 'E-posta zorunlu',
      password: 'Şifre',
      passwordRequired: 'Şifre zorunlu',
      submit: 'Giriş Yap',
      success: 'Giriş başarılı',
    },
    admin: {
      managementPanel: 'Yönetim Paneli',
      operationsPanel: 'Operasyon Paneli',
      pending: 'Bekleyen',
      activeOrder: 'Aktif Sipariş',
      liveOperation: 'Canlı Operasyon',
      adminSubtitle: 'Mutfak, sipariş, masa, QR, menü ve ekip yönetimi',
      staffSubtitle: 'Mutfak, sipariş ve müşteri istekleri',
      realtimeOn: 'Canlı bağlantı açık',
      realtimeOff: 'Canlı bağlantı kapalı',
      soundTest: 'Ses Testi',
      enableSound: 'Sesi Aç',
      tables: 'masa',
      activeOrders: 'aktif sipariş',
      served: 'servis edildi',
      ratings: 'puan',
      tableMetric: 'Masa',
      productMetric: 'Ürün',
      orderMetric: 'Sipariş',
      servedMetric: 'Servis Edildi',
      pendingRequestMetric: 'Bekleyen İstek',
      overallRating: 'Genel Puan',
      tabs: {
        overview: 'Genel Bakış',
        orders: 'Sipariş Geçmişi',
        requests: 'İstek Geçmişi',
        feedbacks: 'Puanlar',
        tables: 'Masalar ve QR',
        categories: 'Kategoriler',
        products: 'Ürünler',
        users: 'Ekip',
        restaurant: 'Restoran',
      },
      sections: {
        pendingRequests: 'Bekleyen İstekler',
        kitchen: 'Mutfak',
        tables: 'Masalar',
        users: 'Kullanıcılar',
        restaurantInfo: 'Restoran Bilgisi',
        waiterCalls: 'Garson Çağrıları',
        billRequests: 'Hesap İstekleri',
        customerRatings: 'Müşteri Puanları',
      },
      actions: {
        add: 'Ekle',
        edit: 'Düzenle',
        delete: 'Sil',
        confirmDelete: 'Silinsin mi?',
        paid: 'Ödendi',
        approve: 'Onayla',
        close: 'Kapat',
        startPreparing: 'Hazırlamaya Başla',
        markReady: 'Hazır',
        markServed: 'Servis Edildi',
        cancelOrder: 'Siparişi İptal Et',
        editRestaurant: 'Restoranı Düzenle',
        downloadPdf: 'PDF İndir',
      },
      columns: {
        table: 'Masa',
        code: 'Kod',
        qrLink: 'QR Link',
        qr: 'QR',
        active: 'Aktif',
        name: 'Ad',
        description: 'Açıklama',
        category: 'Kategori',
        price: 'Fiyat',
        available: 'Satışta',
        action: 'İşlem',
        fullName: 'Ad Soyad',
        email: 'E-posta',
        role: 'Rol',
        updatedAt: 'Güncellendi',
        status: 'Durum',
        total: 'Toplam',
        date: 'Tarih',
        product: 'Ürün',
        quantity: 'Adet',
        productNote: 'Ürün Notu',
        unit: 'Birim',
        message: 'Mesaj',
        note: 'Not',
        createdAt: 'Oluşturuldu',
        order: 'Sipariş',
        overall: 'Genel',
        food: 'Yemek',
        service: 'Servis',
        speed: 'Hız',
        cleanliness: 'Temizlik',
        comment: 'Yorum',
      },
      forms: {
        restaurantName: 'Restoran Adı',
        phone: 'Telefon',
        address: 'Adres',
        tableNumber: 'Masa Numarası',
        categoryName: 'Kategori Adı',
        productName: 'Ürün Adı',
        imageUrl: 'Görsel URL',
        password: 'Parola',
        categoryPlaceholder: 'Kategori seçin',
        categoryNotFound: 'Kategori bulunamadı',
        passwordKeep: 'Boş bırakırsanız mevcut parola korunur.',
        required: {
          restaurantName: 'Restoran adı zorunlu',
          tableNumber: 'Masa numarası zorunlu',
          categoryName: 'Kategori adı zorunlu',
          category: 'Kategori zorunlu',
          productName: 'Ürün adı zorunlu',
          price: 'Fiyat zorunlu',
          fullName: 'Ad soyad zorunlu',
          email: 'E-posta zorunlu',
          validEmail: 'Geçerli e-posta girin',
          password: 'Kaydetmek için parola girin',
          role: 'Rol zorunlu',
        },
      },
      messages: {
        saved: 'Kaydedildi',
        deleted: 'Silindi',
        loggedOut: 'Çıkış yapıldı',
        qrFailed: 'QR kod hazırlanamadı',
        orderStatusUpdated: 'Sipariş durumu güncellendi',
        cancellationReasonRequired: 'Müşteriye gösterilecek iptal nedenini girin',
        waiterApproved: 'Garson çağrısı onaylandı',
        waiterClosed: 'Garson çağrısı kapatıldı',
        billPaid: 'Hesap isteği ödendi olarak işaretlendi',
        billClosed: 'Hesap isteği kapatıldı',
        soundEnabled: 'Bildirim sesi aktif',
        soundBlocked: 'Tarayıcı sesi engelledi. Sayfayla etkileşime geçip tekrar deneyin.',
        productsShown: 'ürün gösteriliyor',
        allCategories: 'Tüm kategoriler',
        emptyKitchen: 'Mutfakta aktif sipariş yok',
        emptyRequests: 'Bekleyen garson çağrısı veya hesap isteği yok',
        waiterCall: 'Garson Çağrısı',
        billRequest: 'Hesap İsteği',
        defaultWaiterMessage: 'Müşteri garson çağırıyor',
        defaultBillMessage: 'Müşteri hesap istiyor',
        customerCancellationInfo: 'Müşteri bu nedeni sipariş takibinde görecek.',
        cancellationPlaceholder: 'Örn. Seçilen ürün stokta kalmadı.',
        orderNote: 'Sipariş notu',
        cancellationReason: 'İptal nedeni',
        newOrderTitle: 'Yeni sipariş',
        newOrderMessage: 'yeni sipariş verdi.',
        waiterCallTitle: 'Garson çağrısı',
        waiterCallMessage: 'garson çağırdı.',
        billRequestTitle: 'Hesap isteği',
        billRequestMessage: 'hesap istedi.',
        feedbackTitle: 'Yeni puanlama',
        feedbackMessage: 'yeni puanlama gönderdi.',
      },
      modalNames: {
        restaurant: 'Restoran',
        table: 'Masa',
        category: 'Kategori',
        product: 'Ürün',
        user: 'Kullanıcı',
      },
      states: {
        active: 'Aktif',
        inactive: 'Pasif',
        admin: 'Yönetici',
        staff: 'Personel',
        OPEN: 'Açık',
        PENDING: 'Yeni',
        IN_PROGRESS: 'İşlemde',
        PREPARING: 'Hazırlanıyor',
        READY: 'Hazır',
        SERVED: 'Servis Edildi',
        COMPLETED: 'Tamamlandı',
        PAID: 'Ödendi',
        CANCELLED: 'İptal',
      },
    },
    menu: {
      table: 'Masa',
      hero: 'QR menüden sipariş verin, garson çağırın ve sipariş durumunu anlık takip edin.',
      callWaiter: 'Garson Çağır',
      requestBill: 'Hesap İste',
      cart: 'Sepet',
      menu: 'Menü',
      myOrders: 'Siparişlerim',
      search: 'Ürün ara',
      add: 'Ekle',
      emptyCategory: 'Bu kategoride ürün yok',
      noOrders: 'Henüz sipariş verilmedi',
      unavailableTitle: 'Menü erişime kapalı',
      unavailableSubtitle: 'Bu QR kod için aktif bir masa menüsü bulunamadı.',
      order: 'Sipariş',
      total: 'Toplam',
      cancelled: 'Sipariş iptal edildi',
      cancelledDescription: 'Restoran siparişinizi iptal etti.',
      feedbackReceived: 'Değerlendirmeniz alındı',
      feedbackDescription: 'Geri bildiriminiz restoran yönetimine iletildi.',
      cartSelected: 'ürün seçildi',
      cartDraft: 'Siparişiniz burada hazırlanır',
      payableTotal: 'Ödenecek Toplam',
      placeOrder: 'Sipariş Ver',
      cartEmpty: 'Sepet boş',
      productNote: 'Ürün notu',
      orderNote: 'Sipariş Notu',
      addedToCart: 'sepete eklendi',
      orderReceived: 'Sipariş alındı',
      orderSent: 'Siparişiniz mutfağa iletildi. Durumunu bu ekrandan takip edebilirsiniz.',
      waiterCalled: 'Garson çağrıldı',
      billSent: 'Hesap isteği gönderildi',
      billNote: 'Hesap isteğine not ekleyin',
      waiterNote: 'Garsona mesaj ekleyin',
      send: 'Gönder',
      unitPrice: 'birim fiyat',
      orderNotePlaceholder: 'Örn. hepsi birlikte gelsin',
      feedbackThanks: 'Puanınız için teşekkürler',
      quantity: 'Adet',
      defaultWaiterMessage: 'Müşteri garson çağırıyor',
      defaultBillMessage: 'Müşteri hesap istiyor',
      rateExperience: 'Deneyiminizi puanlayın',
      rateDescription: 'Yıldızlar ve kısa notunuz hizmet kalitesini iyileştirmek için kullanılır.',
      foodQuality: 'Yemek kalitesi',
      service: 'Servis',
      speed: 'Hız',
      cleanliness: 'Temizlik',
      overallSatisfaction: 'Genel memnuniyet',
      optionalComment: 'İsteğe bağlı yorumunuz',
      sendRating: 'Puanımı Gönder',
    },
    status: {
      PENDING: 'Alındı',
      PREPARING: 'Hazırlanıyor',
      READY: 'Hazır',
      SERVED: 'Servis Edildi',
      CANCELLED: 'İptal',
    },
  },
  en: {
    common: {
      language: 'Language',
      theme: 'Theme',
      light: 'Light',
      dark: 'Dark',
      refresh: 'Refresh',
      logout: 'Logout',
      save: 'Save',
      cancel: 'Cancel',
      close: 'Close',
      openMenu: 'Open Menu',
      staff: 'Staff',
      admin: 'Admin',
    },
    login: {
      title: 'Admin Login',
      subtitle: 'Continue with your authorized account.',
      description: 'Management panel for QR menu, kitchen, and service operations.',
      email: 'Email',
      emailRequired: 'Email is required',
      password: 'Password',
      passwordRequired: 'Password is required',
      submit: 'Sign In',
      success: 'Signed in successfully',
    },
    admin: {
      managementPanel: 'Management Panel',
      operationsPanel: 'Operations Panel',
      pending: 'Pending',
      activeOrder: 'Active Orders',
      liveOperation: 'Live Operation',
      adminSubtitle: 'Kitchen, orders, tables, QR, menu, and team management',
      staffSubtitle: 'Kitchen, orders, and customer requests',
      realtimeOn: 'Live connection on',
      realtimeOff: 'Live connection off',
      soundTest: 'Test Sound',
      enableSound: 'Enable Sound',
      tables: 'tables',
      activeOrders: 'active orders',
      served: 'served',
      ratings: 'ratings',
      tableMetric: 'Tables',
      productMetric: 'Products',
      orderMetric: 'Orders',
      servedMetric: 'Served',
      pendingRequestMetric: 'Pending Requests',
      overallRating: 'Overall Rating',
      tabs: {
        overview: 'Overview',
        orders: 'Order History',
        requests: 'Request History',
        feedbacks: 'Ratings',
        tables: 'Tables and QR',
        categories: 'Categories',
        products: 'Products',
        users: 'Team',
        restaurant: 'Restaurant',
      },
      sections: {
        pendingRequests: 'Pending Requests',
        kitchen: 'Kitchen',
        tables: 'Tables',
        users: 'Users',
        restaurantInfo: 'Restaurant Info',
        waiterCalls: 'Waiter Calls',
        billRequests: 'Bill Requests',
        customerRatings: 'Customer Ratings',
      },
      actions: {
        add: 'Add',
        edit: 'Edit',
        delete: 'Delete',
        confirmDelete: 'Delete?',
        paid: 'Paid',
        approve: 'Approve',
        close: 'Close',
        startPreparing: 'Start Preparing',
        markReady: 'Ready',
        markServed: 'Served',
        cancelOrder: 'Cancel Order',
        editRestaurant: 'Edit Restaurant',
        downloadPdf: 'Download PDF',
      },
      columns: {
        table: 'Table',
        code: 'Code',
        qrLink: 'QR Link',
        qr: 'QR',
        active: 'Active',
        name: 'Name',
        description: 'Description',
        category: 'Category',
        price: 'Price',
        available: 'Available',
        action: 'Action',
        fullName: 'Full Name',
        email: 'Email',
        role: 'Role',
        updatedAt: 'Updated',
        status: 'Status',
        total: 'Total',
        date: 'Date',
        product: 'Product',
        quantity: 'Qty',
        productNote: 'Product Note',
        unit: 'Unit',
        message: 'Message',
        note: 'Note',
        createdAt: 'Created',
        order: 'Order',
        overall: 'Overall',
        food: 'Food',
        service: 'Service',
        speed: 'Speed',
        cleanliness: 'Cleanliness',
        comment: 'Comment',
      },
      forms: {
        restaurantName: 'Restaurant Name',
        phone: 'Phone',
        address: 'Address',
        tableNumber: 'Table Number',
        categoryName: 'Category Name',
        productName: 'Product Name',
        imageUrl: 'Image URL',
        password: 'Password',
        categoryPlaceholder: 'Select a category',
        categoryNotFound: 'No category found',
        passwordKeep: 'Leave blank to keep the current password.',
        required: {
          restaurantName: 'Restaurant name is required',
          tableNumber: 'Table number is required',
          categoryName: 'Category name is required',
          category: 'Category is required',
          productName: 'Product name is required',
          price: 'Price is required',
          fullName: 'Full name is required',
          email: 'Email is required',
          validEmail: 'Enter a valid email',
          password: 'Enter a password to save',
          role: 'Role is required',
        },
      },
      messages: {
        saved: 'Saved',
        deleted: 'Deleted',
        loggedOut: 'Logged out',
        qrFailed: 'QR code could not be prepared',
        orderStatusUpdated: 'Order status updated',
        cancellationReasonRequired: 'Enter the cancellation reason shown to the customer',
        waiterApproved: 'Waiter call approved',
        waiterClosed: 'Waiter call closed',
        billPaid: 'Bill request marked as paid',
        billClosed: 'Bill request closed',
        soundEnabled: 'Notification sound enabled',
        soundBlocked: 'The browser blocked sound. Interact with the page and try again.',
        productsShown: 'products shown',
        allCategories: 'All categories',
        emptyKitchen: 'No active orders in the kitchen',
        emptyRequests: 'No pending waiter calls or bill requests',
        waiterCall: 'Waiter Call',
        billRequest: 'Bill Request',
        defaultWaiterMessage: 'Customer is calling a waiter',
        defaultBillMessage: 'Customer is requesting the bill',
        customerCancellationInfo: 'The customer will see this reason in order tracking.',
        cancellationPlaceholder: 'E.g. selected product is out of stock.',
        orderNote: 'Order note',
        cancellationReason: 'Cancellation reason',
        newOrderTitle: 'New order',
        newOrderMessage: 'placed a new order.',
        waiterCallTitle: 'Waiter call',
        waiterCallMessage: 'called a waiter.',
        billRequestTitle: 'Bill request',
        billRequestMessage: 'requested the bill.',
        feedbackTitle: 'New rating',
        feedbackMessage: 'sent a new rating.',
      },
      modalNames: {
        restaurant: 'Restaurant',
        table: 'Table',
        category: 'Category',
        product: 'Product',
        user: 'User',
      },
      states: {
        active: 'Active',
        inactive: 'Inactive',
        admin: 'Admin',
        staff: 'Staff',
        OPEN: 'Open',
        PENDING: 'New',
        IN_PROGRESS: 'In Progress',
        PREPARING: 'Preparing',
        READY: 'Ready',
        SERVED: 'Served',
        COMPLETED: 'Completed',
        PAID: 'Paid',
        CANCELLED: 'Cancelled',
      },
    },
    menu: {
      table: 'Table',
      hero: 'Order from the QR menu, call a waiter, and track your order live.',
      callWaiter: 'Call Waiter',
      requestBill: 'Request Bill',
      cart: 'Cart',
      menu: 'Menu',
      myOrders: 'My Orders',
      search: 'Search products',
      add: 'Add',
      emptyCategory: 'No products in this category',
      noOrders: 'No orders yet',
      unavailableTitle: 'Menu unavailable',
      unavailableSubtitle: 'No active table menu was found for this QR code.',
      order: 'Order',
      total: 'Total',
      cancelled: 'Order cancelled',
      cancelledDescription: 'The restaurant cancelled your order.',
      feedbackReceived: 'Your rating was received',
      feedbackDescription: 'Your feedback was sent to restaurant management.',
      cartSelected: 'items selected',
      cartDraft: 'Your order will be prepared here',
      payableTotal: 'Amount Due',
      placeOrder: 'Place Order',
      cartEmpty: 'Cart is empty',
      productNote: 'Product note',
      orderNote: 'Order Note',
      addedToCart: 'added to cart',
      orderReceived: 'Order received',
      orderSent: 'Your order was sent to the kitchen. You can track its status here.',
      waiterCalled: 'Waiter called',
      billSent: 'Bill request sent',
      billNote: 'Add a note to the bill request',
      waiterNote: 'Add a message for the waiter',
      send: 'Send',
      unitPrice: 'unit price',
      orderNotePlaceholder: 'E.g. bring everything together',
      feedbackThanks: 'Thanks for your rating',
      quantity: 'Qty',
      defaultWaiterMessage: 'Customer is calling a waiter',
      defaultBillMessage: 'Customer is requesting the bill',
      rateExperience: 'Rate your experience',
      rateDescription: 'Your stars and short note are used to improve service quality.',
      foodQuality: 'Food quality',
      service: 'Service',
      speed: 'Speed',
      cleanliness: 'Cleanliness',
      overallSatisfaction: 'Overall satisfaction',
      optionalComment: 'Optional comment',
      sendRating: 'Send My Rating',
    },
    status: {
      PENDING: 'Received',
      PREPARING: 'Preparing',
      READY: 'Ready',
      SERVED: 'Served',
      CANCELLED: 'Cancelled',
    },
  },
  de: {
    common: {
      language: 'Sprache',
      theme: 'Design',
      light: 'Hell',
      dark: 'Dunkel',
      refresh: 'Aktualisieren',
      logout: 'Abmelden',
      save: 'Speichern',
      cancel: 'Abbrechen',
      close: 'Schließen',
      openMenu: 'Menü Öffnen',
      staff: 'Personal',
      admin: 'Admin',
    },
    login: {
      title: 'Admin Anmeldung',
      subtitle: 'Mit autorisiertem Konto fortfahren.',
      description: 'Verwaltung für QR-Menü, Küche und Serviceabläufe.',
      email: 'E-Mail',
      emailRequired: 'E-Mail ist erforderlich',
      password: 'Passwort',
      passwordRequired: 'Passwort ist erforderlich',
      submit: 'Anmelden',
      success: 'Erfolgreich angemeldet',
    },
    admin: {
      managementPanel: 'Verwaltung',
      operationsPanel: 'Betrieb',
      pending: 'Wartend',
      activeOrder: 'Aktive Bestellungen',
      liveOperation: 'Live-Betrieb',
      adminSubtitle: 'Küche, Bestellungen, Tische, QR, Menü und Teamverwaltung',
      staffSubtitle: 'Küche, Bestellungen und Gästewünsche',
      realtimeOn: 'Live-Verbindung aktiv',
      realtimeOff: 'Live-Verbindung aus',
      soundTest: 'Ton Testen',
      enableSound: 'Ton Aktivieren',
      tables: 'Tische',
      activeOrders: 'aktive Bestellungen',
      served: 'serviert',
      ratings: 'Bewertungen',
      tableMetric: 'Tische',
      productMetric: 'Produkte',
      orderMetric: 'Bestellungen',
      servedMetric: 'Serviert',
      pendingRequestMetric: 'Wartende Wünsche',
      overallRating: 'Gesamtbewertung',
      tabs: {
        overview: 'Übersicht',
        orders: 'Bestellverlauf',
        requests: 'Anfrageverlauf',
        feedbacks: 'Bewertungen',
        tables: 'Tische und QR',
        categories: 'Kategorien',
        products: 'Produkte',
        users: 'Team',
        restaurant: 'Restaurant',
      },
      sections: {
        pendingRequests: 'Wartende Anfragen',
        kitchen: 'Küche',
        tables: 'Tische',
        users: 'Benutzer',
        restaurantInfo: 'Restaurantinfo',
        waiterCalls: 'Service-Rufe',
        billRequests: 'Rechnungsanfragen',
        customerRatings: 'Kundenbewertungen',
      },
      actions: {
        add: 'Hinzufügen',
        edit: 'Bearbeiten',
        delete: 'Löschen',
        confirmDelete: 'Löschen?',
        paid: 'Bezahlt',
        approve: 'Bestätigen',
        close: 'Schließen',
        startPreparing: 'Zubereitung starten',
        markReady: 'Bereit',
        markServed: 'Serviert',
        cancelOrder: 'Bestellung stornieren',
        editRestaurant: 'Restaurant bearbeiten',
        downloadPdf: 'PDF herunterladen',
      },
      columns: {
        table: 'Tisch',
        code: 'Code',
        qrLink: 'QR-Link',
        qr: 'QR',
        active: 'Aktiv',
        name: 'Name',
        description: 'Beschreibung',
        category: 'Kategorie',
        price: 'Preis',
        available: 'Verfügbar',
        action: 'Aktion',
        fullName: 'Vollständiger Name',
        email: 'E-Mail',
        role: 'Rolle',
        updatedAt: 'Aktualisiert',
        status: 'Status',
        total: 'Gesamt',
        date: 'Datum',
        product: 'Produkt',
        quantity: 'Menge',
        productNote: 'Produktnotiz',
        unit: 'Einheit',
        message: 'Nachricht',
        note: 'Notiz',
        createdAt: 'Erstellt',
        order: 'Bestellung',
        overall: 'Gesamt',
        food: 'Essen',
        service: 'Service',
        speed: 'Geschwindigkeit',
        cleanliness: 'Sauberkeit',
        comment: 'Kommentar',
      },
      forms: {
        restaurantName: 'Restaurantname',
        phone: 'Telefon',
        address: 'Adresse',
        tableNumber: 'Tischnummer',
        categoryName: 'Kategoriename',
        productName: 'Produktname',
        imageUrl: 'Bild-URL',
        password: 'Passwort',
        categoryPlaceholder: 'Kategorie auswählen',
        categoryNotFound: 'Keine Kategorie gefunden',
        passwordKeep: 'Leer lassen, um das aktuelle Passwort beizubehalten.',
        required: {
          restaurantName: 'Restaurantname ist erforderlich',
          tableNumber: 'Tischnummer ist erforderlich',
          categoryName: 'Kategoriename ist erforderlich',
          category: 'Kategorie ist erforderlich',
          productName: 'Produktname ist erforderlich',
          price: 'Preis ist erforderlich',
          fullName: 'Vollständiger Name ist erforderlich',
          email: 'E-Mail ist erforderlich',
          validEmail: 'Gültige E-Mail eingeben',
          password: 'Passwort zum Speichern eingeben',
          role: 'Rolle ist erforderlich',
        },
      },
      messages: {
        saved: 'Gespeichert',
        deleted: 'Gelöscht',
        loggedOut: 'Abgemeldet',
        qrFailed: 'QR-Code konnte nicht vorbereitet werden',
        orderStatusUpdated: 'Bestellstatus aktualisiert',
        cancellationReasonRequired: 'Stornogrund für den Kunden eingeben',
        waiterApproved: 'Service-Ruf bestätigt',
        waiterClosed: 'Service-Ruf geschlossen',
        billPaid: 'Rechnungsanfrage als bezahlt markiert',
        billClosed: 'Rechnungsanfrage geschlossen',
        soundEnabled: 'Benachrichtigungston aktiviert',
        soundBlocked: 'Der Browser hat den Ton blockiert. Interagieren Sie mit der Seite und versuchen Sie es erneut.',
        productsShown: 'Produkte angezeigt',
        allCategories: 'Alle Kategorien',
        emptyKitchen: 'Keine aktiven Bestellungen in der Küche',
        emptyRequests: 'Keine wartenden Service-Rufe oder Rechnungsanfragen',
        waiterCall: 'Service-Ruf',
        billRequest: 'Rechnungsanfrage',
        defaultWaiterMessage: 'Kunde ruft den Service',
        defaultBillMessage: 'Kunde möchte die Rechnung',
        customerCancellationInfo: 'Der Kunde sieht diesen Grund in der Bestellverfolgung.',
        cancellationPlaceholder: 'Z. B. ausgewähltes Produkt ist nicht auf Lager.',
        orderNote: 'Bestellnotiz',
        cancellationReason: 'Stornogrund',
        newOrderTitle: 'Neue Bestellung',
        newOrderMessage: 'hat eine neue Bestellung aufgegeben.',
        waiterCallTitle: 'Service-Ruf',
        waiterCallMessage: 'hat den Service gerufen.',
        billRequestTitle: 'Rechnungsanfrage',
        billRequestMessage: 'möchte die Rechnung.',
        feedbackTitle: 'Neue Bewertung',
        feedbackMessage: 'hat eine neue Bewertung gesendet.',
      },
      modalNames: {
        restaurant: 'Restaurant',
        table: 'Tisch',
        category: 'Kategorie',
        product: 'Produkt',
        user: 'Benutzer',
      },
      states: {
        active: 'Aktiv',
        inactive: 'Inaktiv',
        admin: 'Admin',
        staff: 'Personal',
        OPEN: 'Offen',
        PENDING: 'Neu',
        IN_PROGRESS: 'In Bearbeitung',
        PREPARING: 'In Zubereitung',
        READY: 'Bereit',
        SERVED: 'Serviert',
        COMPLETED: 'Abgeschlossen',
        PAID: 'Bezahlt',
        CANCELLED: 'Storniert',
      },
    },
    menu: {
      table: 'Tisch',
      hero: 'Bestellen Sie per QR-Menü, rufen Sie den Service und verfolgen Sie Ihre Bestellung live.',
      callWaiter: 'Service Rufen',
      requestBill: 'Rechnung Anfordern',
      cart: 'Warenkorb',
      menu: 'Menü',
      myOrders: 'Meine Bestellungen',
      search: 'Produkte suchen',
      add: 'Hinzufügen',
      emptyCategory: 'Keine Produkte in dieser Kategorie',
      noOrders: 'Noch keine Bestellungen',
      unavailableTitle: 'Menü nicht verfügbar',
      unavailableSubtitle: 'Für diesen QR-Code wurde kein aktives Tischmenü gefunden.',
      order: 'Bestellung',
      total: 'Gesamt',
      cancelled: 'Bestellung storniert',
      cancelledDescription: 'Das Restaurant hat Ihre Bestellung storniert.',
      feedbackReceived: 'Ihre Bewertung wurde erfasst',
      feedbackDescription: 'Ihr Feedback wurde an die Restaurantleitung gesendet.',
      cartSelected: 'Artikel ausgewählt',
      cartDraft: 'Ihre Bestellung wird hier vorbereitet',
      payableTotal: 'Zu Zahlen',
      placeOrder: 'Bestellen',
      cartEmpty: 'Warenkorb ist leer',
      productNote: 'Produktnotiz',
      orderNote: 'Bestellnotiz',
      addedToCart: 'zum Warenkorb hinzugefügt',
      orderReceived: 'Bestellung empfangen',
      orderSent: 'Ihre Bestellung wurde an die Küche gesendet. Sie können den Status hier verfolgen.',
      waiterCalled: 'Service wurde gerufen',
      billSent: 'Rechnungsanfrage gesendet',
      billNote: 'Notiz zur Rechnungsanfrage hinzufügen',
      waiterNote: 'Nachricht an den Service hinzufügen',
      send: 'Senden',
      unitPrice: 'Stückpreis',
      orderNotePlaceholder: 'Z. B. alles zusammen bringen',
      feedbackThanks: 'Danke für Ihre Bewertung',
      quantity: 'Menge',
      defaultWaiterMessage: 'Der Gast ruft den Service',
      defaultBillMessage: 'Der Gast bittet um die Rechnung',
      rateExperience: 'Bewerten Sie Ihr Erlebnis',
      rateDescription: 'Ihre Sterne und kurze Notiz helfen, die Servicequalität zu verbessern.',
      foodQuality: 'Essensqualität',
      service: 'Service',
      speed: 'Geschwindigkeit',
      cleanliness: 'Sauberkeit',
      overallSatisfaction: 'Gesamtzufriedenheit',
      optionalComment: 'Optionaler Kommentar',
      sendRating: 'Bewertung Senden',
    },
    status: {
      PENDING: 'Empfangen',
      PREPARING: 'In Zubereitung',
      READY: 'Bereit',
      SERVED: 'Serviert',
      CANCELLED: 'Storniert',
    },
  },
  ar: {
    common: {
      language: 'اللغة',
      theme: 'المظهر',
      light: 'فاتح',
      dark: 'داكن',
      refresh: 'تحديث',
      logout: 'تسجيل الخروج',
      save: 'حفظ',
      cancel: 'إلغاء',
      close: 'إغلاق',
      openMenu: 'فتح القائمة',
      staff: 'الموظف',
      admin: 'المدير',
    },
    login: {
      title: 'تسجيل دخول الإدارة',
      subtitle: 'تابع باستخدام حسابك المصرح.',
      description: 'لوحة إدارة لقائمة QR والمطبخ وعمليات الخدمة.',
      email: 'البريد الإلكتروني',
      emailRequired: 'البريد الإلكتروني مطلوب',
      password: 'كلمة المرور',
      passwordRequired: 'كلمة المرور مطلوبة',
      submit: 'تسجيل الدخول',
      success: 'تم تسجيل الدخول بنجاح',
    },
    admin: {
      managementPanel: 'لوحة الإدارة',
      operationsPanel: 'لوحة العمليات',
      pending: 'قيد الانتظار',
      activeOrder: 'الطلبات النشطة',
      liveOperation: 'العمليات المباشرة',
      adminSubtitle: 'إدارة المطبخ والطلبات والطاولات وQR والقائمة والفريق',
      staffSubtitle: 'المطبخ والطلبات وطلبات العملاء',
      realtimeOn: 'الاتصال المباشر مفعل',
      realtimeOff: 'الاتصال المباشر مغلق',
      soundTest: 'اختبار الصوت',
      enableSound: 'تفعيل الصوت',
      tables: 'طاولة',
      activeOrders: 'طلبات نشطة',
      served: 'تم تقديمها',
      ratings: 'تقييم',
      tableMetric: 'الطاولات',
      productMetric: 'المنتجات',
      orderMetric: 'الطلبات',
      servedMetric: 'تم التقديم',
      pendingRequestMetric: 'طلبات معلقة',
      overallRating: 'التقييم العام',
      tabs: {
        overview: 'نظرة عامة',
        orders: 'سجل الطلبات',
        requests: 'سجل الطلبات الخدمية',
        feedbacks: 'التقييمات',
        tables: 'الطاولات وQR',
        categories: 'الفئات',
        products: 'المنتجات',
        users: 'الفريق',
        restaurant: 'المطعم',
      },
      sections: {
        pendingRequests: 'الطلبات المعلقة',
        kitchen: 'المطبخ',
        tables: 'الطاولات',
        users: 'المستخدمون',
        restaurantInfo: 'معلومات المطعم',
        waiterCalls: 'طلبات النادل',
        billRequests: 'طلبات الحساب',
        customerRatings: 'تقييمات العملاء',
      },
      actions: {
        add: 'إضافة',
        edit: 'تعديل',
        delete: 'حذف',
        confirmDelete: 'هل تريد الحذف؟',
        paid: 'مدفوع',
        approve: 'تأكيد',
        close: 'إغلاق',
        startPreparing: 'بدء التحضير',
        markReady: 'جاهز',
        markServed: 'تم التقديم',
        cancelOrder: 'إلغاء الطلب',
        editRestaurant: 'تعديل المطعم',
        downloadPdf: 'تنزيل PDF',
      },
      columns: {
        table: 'الطاولة',
        code: 'الرمز',
        qrLink: 'رابط QR',
        qr: 'QR',
        active: 'نشط',
        name: 'الاسم',
        description: 'الوصف',
        category: 'الفئة',
        price: 'السعر',
        available: 'متاح',
        action: 'الإجراء',
        fullName: 'الاسم الكامل',
        email: 'البريد الإلكتروني',
        role: 'الدور',
        updatedAt: 'آخر تحديث',
        status: 'الحالة',
        total: 'الإجمالي',
        date: 'التاريخ',
        product: 'المنتج',
        quantity: 'الكمية',
        productNote: 'ملاحظة المنتج',
        unit: 'الوحدة',
        message: 'الرسالة',
        note: 'ملاحظة',
        createdAt: 'تم الإنشاء',
        order: 'الطلب',
        overall: 'عام',
        food: 'الطعام',
        service: 'الخدمة',
        speed: 'السرعة',
        cleanliness: 'النظافة',
        comment: 'تعليق',
      },
      forms: {
        restaurantName: 'اسم المطعم',
        phone: 'الهاتف',
        address: 'العنوان',
        tableNumber: 'رقم الطاولة',
        categoryName: 'اسم الفئة',
        productName: 'اسم المنتج',
        imageUrl: 'رابط الصورة',
        password: 'كلمة المرور',
        categoryPlaceholder: 'اختر فئة',
        categoryNotFound: 'لم يتم العثور على فئة',
        passwordKeep: 'اتركه فارغا للاحتفاظ بكلمة المرور الحالية.',
        required: {
          restaurantName: 'اسم المطعم مطلوب',
          tableNumber: 'رقم الطاولة مطلوب',
          categoryName: 'اسم الفئة مطلوب',
          category: 'الفئة مطلوبة',
          productName: 'اسم المنتج مطلوب',
          price: 'السعر مطلوب',
          fullName: 'الاسم الكامل مطلوب',
          email: 'البريد الإلكتروني مطلوب',
          validEmail: 'أدخل بريدا إلكترونيا صالحا',
          password: 'أدخل كلمة مرور للحفظ',
          role: 'الدور مطلوب',
        },
      },
      messages: {
        saved: 'تم الحفظ',
        deleted: 'تم الحذف',
        loggedOut: 'تم تسجيل الخروج',
        qrFailed: 'تعذر تجهيز رمز QR',
        orderStatusUpdated: 'تم تحديث حالة الطلب',
        cancellationReasonRequired: 'أدخل سبب الإلغاء الذي سيظهر للعميل',
        waiterApproved: 'تم تأكيد طلب النادل',
        waiterClosed: 'تم إغلاق طلب النادل',
        billPaid: 'تم وضع علامة مدفوع على طلب الحساب',
        billClosed: 'تم إغلاق طلب الحساب',
        soundEnabled: 'تم تفعيل صوت الإشعارات',
        soundBlocked: 'حظر المتصفح الصوت. تفاعل مع الصفحة وحاول مرة أخرى.',
        productsShown: 'منتجات معروضة',
        allCategories: 'كل الفئات',
        emptyKitchen: 'لا توجد طلبات نشطة في المطبخ',
        emptyRequests: 'لا توجد طلبات نادل أو حساب معلقة',
        waiterCall: 'طلب نادل',
        billRequest: 'طلب حساب',
        defaultWaiterMessage: 'العميل يستدعي النادل',
        defaultBillMessage: 'العميل يطلب الحساب',
        customerCancellationInfo: 'سيرى العميل هذا السبب في تتبع الطلب.',
        cancellationPlaceholder: 'مثال: المنتج المحدد غير متوفر.',
        orderNote: 'ملاحظة الطلب',
        cancellationReason: 'سبب الإلغاء',
        newOrderTitle: 'طلب جديد',
        newOrderMessage: 'أرسل طلبا جديدا.',
        waiterCallTitle: 'طلب نادل',
        waiterCallMessage: 'استدعى النادل.',
        billRequestTitle: 'طلب حساب',
        billRequestMessage: 'طلب الحساب.',
        feedbackTitle: 'تقييم جديد',
        feedbackMessage: 'أرسل تقييما جديدا.',
      },
      modalNames: {
        restaurant: 'مطعم',
        table: 'طاولة',
        category: 'فئة',
        product: 'منتج',
        user: 'مستخدم',
      },
      states: {
        active: 'نشط',
        inactive: 'غير نشط',
        admin: 'مدير',
        staff: 'موظف',
        OPEN: 'مفتوح',
        PENDING: 'جديد',
        IN_PROGRESS: 'قيد المعالجة',
        PREPARING: 'قيد التحضير',
        READY: 'جاهز',
        SERVED: 'تم التقديم',
        COMPLETED: 'مكتمل',
        PAID: 'مدفوع',
        CANCELLED: 'ملغي',
      },
    },
    menu: {
      table: 'طاولة',
      hero: 'اطلب من قائمة QR، واستدع النادل، وتابع حالة طلبك مباشرة.',
      callWaiter: 'استدعاء النادل',
      requestBill: 'طلب الحساب',
      cart: 'السلة',
      menu: 'القائمة',
      myOrders: 'طلباتي',
      search: 'ابحث عن المنتجات',
      add: 'إضافة',
      emptyCategory: 'لا توجد منتجات في هذه الفئة',
      noOrders: 'لا توجد طلبات بعد',
      unavailableTitle: 'القائمة غير متاحة',
      unavailableSubtitle: 'لم يتم العثور على قائمة طاولة نشطة لهذا رمز QR.',
      order: 'طلب',
      total: 'الإجمالي',
      cancelled: 'تم إلغاء الطلب',
      cancelledDescription: 'قام المطعم بإلغاء طلبك.',
      feedbackReceived: 'تم استلام تقييمك',
      feedbackDescription: 'تم إرسال ملاحظاتك إلى إدارة المطعم.',
      cartSelected: 'منتجات محددة',
      cartDraft: 'سيتم تجهيز طلبك هنا',
      payableTotal: 'المبلغ المستحق',
      placeOrder: 'إرسال الطلب',
      cartEmpty: 'السلة فارغة',
      productNote: 'ملاحظة المنتج',
      orderNote: 'ملاحظة الطلب',
      addedToCart: 'أضيف إلى السلة',
      orderReceived: 'تم استلام الطلب',
      orderSent: 'تم إرسال طلبك إلى المطبخ. يمكنك متابعة حالته من هذه الشاشة.',
      waiterCalled: 'تم استدعاء النادل',
      billSent: 'تم إرسال طلب الحساب',
      billNote: 'أضف ملاحظة لطلب الحساب',
      waiterNote: 'أضف رسالة للنادل',
      send: 'إرسال',
      unitPrice: 'سعر الوحدة',
      orderNotePlaceholder: 'مثال: أحضر كل شيء معا',
      feedbackThanks: 'شكرا على تقييمك',
      quantity: 'الكمية',
      defaultWaiterMessage: 'العميل يستدعي النادل',
      defaultBillMessage: 'العميل يطلب الحساب',
      rateExperience: 'قيّم تجربتك',
      rateDescription: 'تُستخدم النجوم وملاحظتك القصيرة لتحسين جودة الخدمة.',
      foodQuality: 'جودة الطعام',
      service: 'الخدمة',
      speed: 'السرعة',
      cleanliness: 'النظافة',
      overallSatisfaction: 'الرضا العام',
      optionalComment: 'تعليق اختياري',
      sendRating: 'إرسال تقييمي',
    },
    status: {
      PENDING: 'تم الاستلام',
      PREPARING: 'قيد التحضير',
      READY: 'جاهز',
      SERVED: 'تم التقديم',
      CANCELLED: 'ملغي',
    },
  },
};

const PreferencesContext = createContext(null);

export function PreferencesProvider({ children }) {
  const [language, setLanguageState] = useState(() => localStorage.getItem(LANGUAGE_STORAGE_KEY) || 'tr');
  const [themeMode, setThemeModeState] = useState(() => localStorage.getItem(THEME_STORAGE_KEY) || 'light');

  useEffect(() => {
    localStorage.setItem(LANGUAGE_STORAGE_KEY, language);
    document.documentElement.lang = language;
    document.documentElement.dir = languageDirections[language] || 'ltr';
  }, [language]);

  useEffect(() => {
    localStorage.setItem(THEME_STORAGE_KEY, themeMode);
    document.documentElement.dataset.theme = themeMode;
  }, [themeMode]);

  const value = useMemo(() => {
    const dictionary = translations[language] || translations.tr;
    const t = (key) => key.split('.').reduce((current, part) => current?.[part], dictionary) || key;

    return {
      language,
      setLanguage: setLanguageState,
      themeMode,
      setThemeMode: setThemeModeState,
      toggleTheme: () => setThemeModeState((current) => (current === 'dark' ? 'light' : 'dark')),
      t,
    };
  }, [language, themeMode]);

  return <PreferencesContext.Provider value={value}>{children}</PreferencesContext.Provider>;
}

export function usePreferences() {
  const context = useContext(PreferencesContext);
  if (!context) {
    throw new Error('usePreferences must be used within PreferencesProvider');
  }
  return context;
}
