ALTER TABLE restaurants ADD COLUMN IF NOT EXISTS logo_url VARCHAR(700);
ALTER TABLE restaurants ADD COLUMN IF NOT EXISTS cover_image_url VARCHAR(700);
ALTER TABLE restaurants ADD COLUMN IF NOT EXISTS welcome_message VARCHAR(500);
ALTER TABLE restaurants ADD COLUMN IF NOT EXISTS ordering_enabled BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE restaurants ADD COLUMN IF NOT EXISTS waiter_calls_enabled BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE restaurants ADD COLUMN IF NOT EXISTS bill_requests_enabled BOOLEAN NOT NULL DEFAULT TRUE;

ALTER TABLE orders ADD COLUMN IF NOT EXISTS cancellation_reason VARCHAR(500);
